-- +goose Up
-- +goose StatementBegin
-- +goose ENVSUB ON
GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;
GRANT USAGE on SCHEMA production TO $DATABASE_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA production TO $DATABASE_USER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA production TO $DATABASE_USER;
-- +goose ENVSUB OFF
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose ENVSUB ON
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA production FROM $DATABASE_USER;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA production FROM $DATABASE_USER;
REVOKE USAGE ON SCHEMA production FROM $DATABASE_USER;
REVOKE ALL PRIVILEGES ON DATABASE $DATABASE_NAME FROM $DATABASE_USER;
-- +goose ENVSUB OFF
-- +goose StatementEnd
